### ISSUE TITLE
깃헙 프로필이 테마 제작자로 되어있네요 ^^

### ISSUE THREAD

**Issue by hrmrzizon** [lowapple/lowapple.github.io#1]
![image](https://user-images.githubusercontent.com/7834693/54068632-604f9f00-4292-11e9-8902-2e0e35907afc.png)

**Comment by lowapple** [comment]
앗 죄송합니다. 크게 신경 안쓰고 방치하다 보니 이슈 들어온것도 몰랐네요..

감사합니다. :)
